### ISSUE TITLE
smh

### ISSUE THREAD

**Issue by iGetUploaded** [Exspiravit13/D-DAY-Server_Nuker#1]
Mans just took presser nuker and changed the name and said he made it lmao

**Comment by Exspiravit13** [comment]
Okay 💀

**Comment by Exspiravit13** [comment]
Just looked at presser… have you seen the code? Completely different.

**Comment by iGetUploaded** [comment]
You look at the right presser? look at your lines from 1 to 72 are basically the same all you really did was make it a little compact lmao
https://github.com/17teen/Discord-Presser-Server-Nuker/blob/master/src/index.js

**Comment by Exspiravit13** [comment]
The functions? Functions don’t make a bot 😂 D-DAY is completely different the functions are similar. My timeouts are different and overall structure mine supports ESM presser is not ESM… you have almost all your repos forked I have 1 public repo (also kinda sad you got that many repos and 0 followers cmon bro take a hint)  💀 npm install some bitches and stop tryna ruin peoples rep Join the cord we got shit goin on

**Comment by iGetUploaded** [comment]
mans thinks I care about followers buddy you have 1 chill out 🤡

**Comment by Exspiravit13** [comment]
Better than none 🤡

**Comment by Exspiravit13** [comment]
Haven’t even been on GitHub for a year 🤣 look at all your contributions LMAO

**Comment by iGetUploaded** [comment]
Mans care more about Github contributions  that no one cares about lmao again nice try bozo 🤡🤡

**Comment by Exspiravit13** [comment]
I follow 4 you follow 16 💀 You legit look like a pick me

**Comment by Exspiravit13** [comment]
Most your shit is for discord 🤣 what an L

**Comment by iGetUploaded** [comment]
L ? bro are you hearing yourself?  mans got books liked and discord things bros trying to act tuff 🤡

**Comment by Exspiravit13** [comment]
2 Discord related repos VS however many you got starred 💀 LMAO you been on here for years and got nothing going on 🤣 been on here maybe 2 months

**Comment by Exspiravit13** [comment]
Yk what imma follow your goofy ass just so I can get 5 following ;)

**Comment by iGetUploaded** [comment]
cuz I dont care for posting repos/contributions I like them and to try expose ppl who just skid other ppls projects(you) and try to token log people lmao

**Comment by Exspiravit13** [comment]
I’m not a skid 💀 I’m legit in college CyberSec with a 4.0 lmao you think because it’s similar that I skidded? Presser is the only JS based Nuker that is somewhat popular everything else is in Python I have files from before presser was even posted with the same code lmao but okay 👍🏽

**Comment by iGetUploaded** [comment]
if u so called have files from before presser show proof bud and I forgot who asked wht your gpa was

**Comment by Exspiravit13** [comment]
what*

**Comment by Exspiravit13** [comment]
Wait till I get off work since you want proof lmao imagine that changing anything it can be edited 🤣
